name: yearn-boosted-staker

plugins:
  - name: solidity
  - name: ens
  - name: etherscan
  - name: foundry
  - name: vyper
  - name: tenderly
  - name: alchemy

compile:
  exclude:
    - "*YLockerProxy.sol"
    - "*PrismaLocker.sol"

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.3

solidity: 
  import_remapping:
    - "@openzeppelin/contracts@v4.9.3/=OpenZeppelin/4.9.3"

ethereum:
  default_network: mainnet-fork
  local:
    default_provider: foundry
  
foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy